#!/usr/bin/env python3
"""Generate or check the nextest ignored-test inventory."""

from __future__ import annotations

import argparse
import difflib
import json
import subprocess
import sys
from pathlib import Path


DEFAULT_INVENTORY = Path("ignored-tests.txt")


def nextest_inventory() -> list[str]:
    completed = subprocess.run(
        [
            "cargo",
            "nextest",
            "list",
            "--workspace",
            "--run-ignored",
            "all",
            "--message-format",
            "json",
        ],
        check=True,
        stdout=subprocess.PIPE,
        stderr=sys.stderr,
        text=True,
    )
    payload = None
    for line in completed.stdout.splitlines():
        stripped = line.strip()
        if stripped.startswith('{"rust-build-meta"'):
            payload = json.loads(stripped)
            break
    if payload is None:
        raise RuntimeError("cargo nextest list did not emit JSON test metadata")

    ignored = []
    for suite in payload.get("rust-suites", {}).values():
        package = suite.get("package-name", "<unknown-package>")
        kind = suite.get("kind", "<unknown-kind>")
        binary = suite.get("binary-name", suite.get("binary-id", "<unknown-binary>"))
        for test_name, test in suite.get("testcases", {}).items():
            if test.get("kind") == "test" and test.get("ignored") is True:
                ignored.append(f"{package}::{kind}:{binary}::{test_name}")
    return sorted(ignored)


def render_inventory(entries: list[str]) -> str:
    lines = [
        "# Ignored Test Inventory",
        "#",
        "# Generated by: python3 tools/ignored_tests_inventory.py update",
        "# Checked by: python3 tools/ignored_tests_inventory.py check",
        "#",
        "# This file intentionally records tests marked #[ignore]. Update it when",
        "# a test is newly gated, ungated, renamed, or moved between test targets.",
        f"# Count: {len(entries)}",
        "",
    ]
    lines.extend(entries)
    lines.append("")
    return "\n".join(lines)


def update(path: Path) -> None:
    path.write_text(render_inventory(nextest_inventory()), encoding="utf-8")


def check(path: Path) -> int:
    expected = render_inventory(nextest_inventory())
    try:
        actual = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"{path} is missing; run `python3 tools/ignored_tests_inventory.py update`", file=sys.stderr)
        return 1
    if actual == expected:
        return 0

    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=str(path),
        tofile="generated ignored-test inventory",
    )
    sys.stderr.writelines(diff)
    print(
        f"\n{path} is stale; run `python3 tools/ignored_tests_inventory.py update`",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=["check", "update"])
    parser.add_argument("--path", type=Path, default=DEFAULT_INVENTORY)
    args = parser.parse_args()

    if args.mode == "update":
        update(args.path)
        return 0
    return check(args.path)


if __name__ == "__main__":
    raise SystemExit(main())
